spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      username: wds
      password: narisq
      url: jdbc:oracle:thin:@//172.20.50.51:1521/wds
#rabbitmq相关配置dell-PC
  rabbitmq:
     host: 114.80.231.178 #10.1.30.24
     port: 5671
     username: shuiwen
     password: siti@sw
     publisher-confirms: true
     publisher-returns: true
     virtual-host: shuiwen
     listener:
        simple:
          acknowledge-mode: manual #采用手动应答
          concurrency: 3
          max-concurrency: 3
          retry:
            enabled: false #是否支持重试
          prefetch: 10
server:
  port: 8097

filePath:
  invalidFileDelete: 0    # 无效文件立即删除
  bikeClean: C:/wisdomhydrologic/bikeClean/    # 文件服务器地址
  head: C:/wisdomhydrologic/head/    # 用户头像
  feedback: C:/wisdomhydrologic/feedback/    # 用户反馈

logback:
  logHome: C:/wisdomhydrologic/log/
  logName: wisdomhydrologic