quartz:
  enabled: true

server:
  port: 8081
  context-path: /wisdomhydrologic

spring:
  thymeleaf:
    mode: LEGACYHTML5
  profiles:
     active: prod
  application:
    name: wisdomhydrologic
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
version:
  calversion: "V1.1" # 版本号
  build: 1111 # 小版本号

